### ISSUE TITLE
download_ramlegacy should have an argument to overwrite

### ISSUE THREAD

**Issue by cboettig** [ropensci/ramlegacy#4]
@kshtzgupta1 just noticed this in testing the package in class -- it's nice for any interactive function to also have an optional argument to prevent the interactive behavior.  e.g. `download_ramlegacy()` should have an argument `overwrite` with default being "ask", but which can be set to TRUE or FALSE in the function call to avoid the interactive prompt when you don't want it.  

Are there any other interactive steps we want to fix as well?

**Comment by kshtzgupta1** [comment]
I have added `overwrite` . Maybe we can also add `quiet` as argument which is FALSE by default but if set to TRUE will suppress all the status messages that `download_ramlegacy` usually displays.
