### ISSUE TITLE
New Maintainer Wanted :-)

### ISSUE THREAD

**Issue by maelle** [ropensci/ramlegacy#8]
Or new maintainer team. :smile_cat: 

If you're interested, please comment in the issue.
For more info, see
- [our guidance on Changing package maintainers](https://devguide.ropensci.org/changing-maintainers.html);
- [our Package Curation Policy](https://devguide.ropensci.org/curationpolicy.html).

**Comment by cboettig** [comment]
Thanks @maelle.  I can probably take this on, or happy to work with anyone who wants to join in.

**Comment by maelle** [comment]
@ropensci/admin

**Comment by maelle** [comment]
@cboettig Thanks for volunteering, the package is yours now :wink: I've invited you to a team with admin access to the repo. Please update the DESCRIPTION file when you get a chance. Thanks a ton!!
